[package]
name = "splatfield"
version = "0.1.0"
edition = "2024"

[dependencies]
cubecl = { version = "0.10.0-pre.3", features = ["wgpu", "std", "stdlib"] }
bytemuck = { version = "1.25", features = ["derive"] }
glam = "0.32.1"
egui = "0.34"
eframe = { version = "0.34", default-features = false, features = ["wgpu"] }
wgpu = { version = "29", default-features = false }
serde = { version = "1.0.228", default-features = false, features = ["derive"] }
serde-ply = "0.2.2"
anyhow = "1.0.102"
env_logger = "0.11.9"
log = "0.4"

[dev-dependencies]
rand = "0.10"
criterion = "0.5"

[[bench]]
name = "radix_sort"
harness = false
