[package]
name = "splatfield"
version = "0.1.1"
edition = "2024"

[dependencies]
cubecl = { version = "0.10.0", features = ["wgpu", "std", "stdlib"] }
bytemuck = { version = "1.25", features = ["derive"] }
glam = "0.32.1"
egui = "0.34"
wgpu = "29"
anyhow = "1.0.102"
log = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
eframe = { version = "0.34", default-features = false, features = ["wgpu", "x11", "wayland"] }
pollster = "0.4"
env_logger = "0.11.9"

[target.'cfg(target_arch = "wasm32")'.dependencies]
cubecl-common = { version = "0.10.0", features = ["serde"] }
eframe = { version = "0.34", features = ["wgpu"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["HtmlCanvasElement", "Document", "Element", "Window"] }
console_error_panic_hook = "0.1"
getrandom = { version = "0.4", features = ["wasm_js"] }
serde_json = { version = "1.0", features = ["alloc"] }

[dev-dependencies]
rand = "0.10"
criterion = "0.5"

[[bench]]
name = "radix_sort"
harness = false

[profile.release]
lto = true
opt-level = 's'
codegen-units = 1
panic = "abort"
