[package]
name = "gsam"
version.workspace = true
edition.workspace = true

[dependencies]
ort = { version = "=2.0.0-rc.11", default-features = false, features = [
    "download-binaries",
    "tls-rustls",
    "half",
    "std",
] }
half = "2.7"
anyhow.workspace = true
dirs = "7"
image = { version = "0.25", default-features = false }
tokenizers = { version = "=0.23.2", default-features = false, features = ["fancy-regex"] }
